import Head from 'next/head'
import HomeBanner from '../components/Banner'
import Featured from '../components/Featured'
import HomeLayout from '../components/Layouts'

import SmallNav from '../components/Navbar/SmallNav'
import PopularProducts from '../components/PopularProducts'

export default function Home() {
  return (
    <div className="max-w-screen w-full font-open-sans relative !scrollbar-hide">
      <Head>
        <title>Fresh Mart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-icon.png"></link>
        <link rel="manifest" href="/manifest.json" />
<link href='/icons/icon-192x192.png' rel='icon' type='image/png' sizes='192x192' />
<link href='/icons/icon-256x256.png' rel='icon' type='image/png' sizes='256x256' />

      </Head>

      <div>
        <HomeLayout>
          <div className="fixed bottom-0 z-10 w-full">
            <SmallNav />
          </div>
          <HomeBanner />
          <Featured />
          <PopularProducts />
        </HomeLayout>
      </div>
    </div>
  )
}


export async function getStaticProps(){
  console.log('server running')
  const products =[]
  return {
props:{
  products
},
revalidate:10
  }
}